//// <auto-generated />
//using system;
//using hotelfinder.dataaccess;
//using microsoft.entityframeworkcore;
//using microsoft.entityframeworkcore.infrastructure;
//using microsoft.entityframeworkcore.storage.valueconversion;
//using npgsql.entityframeworkcore.postgresql.metadata;

//namespace hotelfinder.dataaccess.migrations
//{
//    [dbcontext(typeof(hoteldbcontext))]
//    partial class hoteldbcontextmodelsnapshot : modelsnapshot
//    {
//        protected override void buildmodel(modelbuilder modelbuilder)
//        {
//#pragma warning disable 612, 618
//            modelbuilder
//                .useidentitybydefaultcolumns()
//                .hasannotation("relational:maxidentifierlength", 63)
//                .hasannotation("productversion", "5.0.17");

//            modelbuilder.entity("otelfinder.entities.category", b =>
//                {
//                    b.property<int>("id")
//                        .valuegeneratedonadd()
//                        .hascolumntype("integer")
//                        .useidentitybydefaultcolumn();

//                    b.property<string>("name")
//                        .hascolumntype("text");

//                    b.haskey("id");

//                    b.totable("categories");
//                });

//            modelbuilder.entity("otelfinder.entities.city", b =>
//                {
//                    b.property<int>("id")
//                        .valuegeneratedonadd()
//                        .hascolumntype("integer")
//                        .useidentitybydefaultcolumn();

//                    b.property<string>("name")
//                        .hascolumntype("text");

//                    b.haskey("id");

//                    b.totable("cities");
//                });

//            modelbuilder.entity("otelfinder.entities.country", b =>
//                {
//                    b.property<int>("id")
//                        .valuegeneratedonadd()
//                        .hascolumntype("integer")
//                        .useidentitybydefaultcolumn();

//                    b.property<string>("name")
//                        .hascolumntype("text");

//                    b.haskey("id");

//                    b.totable("countries");
//                });

//            modelbuilder.entity("otelfinder.entities.hotel", b =>
//                {
//                    b.property<int>("id")
//                        .valuegeneratedonadd()
//                        .hascolumntype("integer")
//                        .useidentitybydefaultcolumn();

//                    b.property<int?>("categoryid")
//                        .hascolumntype("integer");

//                    b.property<int?>("cityid")
//                        .isrequired()
//                        .hasmaxlength(50)
//                        .hascolumntype("integer");

//                    b.property<int?>("countryid")
//                        .hascolumntype("integer");

//                    b.property<string>("name")
//                        .isrequired()
//                        .hasmaxlength(50)
//                        .hascolumntype("character varying(50)");

//                    b.property<int?>("numberofroom")
//                        .hascolumntype("integer");

//                    b.property<double?>("roomprice")
//                        .hascolumntype("double precision");

//                    b.property<int?>("star")
//                        .hascolumntype("integer");

//                    b.haskey("id");

//                    b.hasindex("categoryid");

//                    b.hasindex("cityid");

//                    b.hasindex("countryid");

//                    b.totable("hotels");
//                });

//            modelbuilder.entity("otelfinder.entities.hotel", b =>
//                {
//                    b.hasone("otelfinder.entities.category", null)
//                        .withmany("hotels")
//                        .hasforeignkey("categoryid");

//                    b.hasone("otelfinder.entities.city", null)
//                        .withmany("hotels")
//                        .hasforeignkey("cityid")
//                        .ondelete(deletebehavior.cascade)
//                        .isrequired();

//                    b.hasone("otelfinder.entities.country", null)
//                        .withmany("hotels")
//                        .hasforeignkey("countryid");
//                });

//            modelbuilder.entity("otelfinder.entities.category", b =>
//                {
//                    b.navigation("hotels");
//                });

//            modelbuilder.entity("otelfinder.entities.city", b =>
//                {
//                    b.navigation("hotels");
//                });

//            modelbuilder.entity("otelfinder.entities.country", b =>
//                {
//                    b.navigation("hotels");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
